name: Regression Tests
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt-get install -y bmake valgrind
    - name: Configure
      run: |
        cat /etc/os-release
        ./configure
        bmake regress
        bmake valgrind
